// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nnc-redesign-editorial/Home.tsx": () => import("../components/mockups/nnc-redesign-editorial/Home.tsx"),
  "./components/mockups/nnc-redesign-botanical/Home.tsx": () => import("../components/mockups/nnc-redesign-botanical/Home.tsx"),
  "./components/mockups/nnc-site/Site.tsx": () => import("../components/mockups/nnc-site/Site.tsx")
};
